### PR TITLE
[TASK] Prepare the 8.7.0 release

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Review by JakeQZ — COMMENTED** [review]
Does now work with Emogrifier-dev on PHP 8.4?

**Comment by oliverklee** [comment]
Sigh. It seems we still need to fix some more places after all for PHP 8.4 compatibility for Emogrifier. (I wonder why the tests  for PHP-CSS-Parser do not catch this.)
https://github.com/MyIntervals/emogrifier/pull/1304

**Comment by JakeQZ** [comment]
> Sigh. It seems we still need to fix some more places after all for PHP 8.4 compatibility for Emogrifier.

Possibly needs something for #677.

> (I wonder why the tests for PHP-CSS-Parser do not catch this.) [MyIntervals/emogrifier#1304](https://github.com/MyIntervals/emogrifier/pull/1304)

That is indeed strange, since we are running unit tests with PHP 8.4, which will surely call `CSSList\Document::render()`.  Are deprecation warnings disabled in the PHPUnit config?

**Comment by oliverklee** [comment]
> Are deprecation warnings disabled in the PHPUnit config?

Indeed: https://github.com/MyIntervals/PHP-CSS-Parser/pull/744

**Comment by oliverklee** [comment]
This should be ready to go now. Emogrifier also is green with the latest v8.x branch: https://github.com/MyIntervals/emogrifier/pull/1304 (ignore the "lowest dependency version" failure)

**Comment by oliverklee** [comment]
Sigh. And another nullable-by-default parameter that isn't covered by the the parser tests yet: https://github.com/MyIntervals/emogrifier/actions/runs/11538536814/job/32117129042?pr=1304

**Comment by oliverklee** [comment]
Now the Emogrifier CI build is green with the latest changes in the v8.x branch of PHP-CSS-Parser: https://github.com/MyIntervals/emogrifier/pull/1304

I think 8.7.0 is ready to get released.

**Review by JakeQZ — APPROVED** [review]
> Now the Emogrifier CI build is green with the latest changes in the v8.x branch of PHP-CSS-Parser: [MyIntervals/emogrifier#1304](https://github.com/MyIntervals/emogrifier/pull/1304)

PHPUnit with `dependencies=lowest` is still failing but that's due to an issue with Symfony.

**Comment by oliverklee** [comment]
I have just released version 8.7.0: https://github.com/MyIntervals/PHP-CSS-Parser/releases/tag/v8.7.0

**Pull request merged**
