### PR TITLE
[CLEANUP] Fix indentation of dependabot configuration

### PR DESCRIPTION
**Pull request by ziegenberg**
It was nothing fancy; It just calmed my inner Monk, who had been upset about the indentation :)

### CODE REVIEW

**Review by oliverklee — COMMENTED** [review]
Thank you for this cleanup PR! :pray:

As far as I can see, this change contradicts the style conventions defined in our `.editorconfig`: https://github.com/MyIntervals/PHP-CSS-Parser/blob/main/.editorconfig#L11

Am I missing something here?

**Comment by ziegenberg** [comment]
The rest of the file has two spaces of indentation. So it's inconsistent with itself. And the other *.yml files also use two spaces of indendation.

**Comment by ziegenberg** [comment]
Anyway, I'm happy to go either way. :) Just trying to make it consistent

**Comment by oliverklee** [comment]
Then let's go with 4 spaces. Would you be willing to create a PR to bring the YAML files in line?

**Comment by ziegenberg** [comment]
I'll amend this PR and file a separate one for the GitHub Actions *.yml files.

**Review by oliverklee — CHANGES_REQUESTED** [review]
Thanks!

**Review by oliverklee — APPROVED** [review]

**Pull request merged**
