### PR TITLE
[TASK] Remove `Rule::setValues`

### PR DESCRIPTION
**Pull request by ziegenberg**
Removing one function after another.

### CODE REVIEW

**Comment by ziegenberg** [comment]
I fixed the changelog message.

**Comment by ziegenberg** [comment]
Rebased and force-pushed.

**Review by JakeQZ — APPROVED** [review]

**Comment by oliverklee** [comment]
@JakeQZ I think you're merging `main` into the PR branches to update them (which is the default way suggested by GitHub AFAIK). Instead, we should rebase the PRs on `main` .

**Comment by JakeQZ** [comment]
> @JakeQZ I think you're merging `main` into the PR branches to update them (which is the default way suggested by GitHub AFAIK). Instead, we should rebase the PRs on `main` .

The GitHub method seemed to work fine in cases with just a conflict in CHANGELOG.  It was quick and easy whilst reviewing to click 'Resolve Conflicts' and simply remove the diff markers (since the conflict was multiple additions at the same line).  However, in #563 there was also a conflict in another file, which I thought I had resolved correctly, then after committing realized I hand't, so tried to revert the merge, spectacularly unsuccessfully.

**Pull request merged**
