### PR TITLE
[TASK] Add more PHP-CS-Fixer rules

### PR DESCRIPTION
**Pull request by oliverklee**
Also drop some rules that are already in included in the used
rulesets.

### CODE REVIEW

**Comment by oliverklee** [comment]
Note: I'll need to add some type casts (in separate PRs) before we can make all files strict.

**Review by JakeQZ — COMMENTED** [review]
> Also drop some rules that are already in included in the used rulesets.

Actually, the rules being removed have the value being set as the default.  So I'm wondering if they should be kept, to be explicit, or removed anyway, to avoid clutter.

Otherwise, this brings the config in line with the Emogrifier project, so we have consistency.

**Comment by oliverklee** [comment]
> Actually, the rules being removed have the value being set as the default. So I'm wondering if they should be kept, to be explicit, or removed anyway, to avoid clutter.

I don’t care much either way - as long as the config file is consistent between our two projects. :-)

**Review by JakeQZ — APPROVED** [review]
> I don’t care much either way - as long as the config file is consistent between our two projects. :-)

Neither do I, TBH.  It was just an observation.  Emogrifier doesn't have them, so for consistency we may as well remove them here.

**Pull request merged**
