### PR TITLE
[CLEANUP] Rector: Add strict return type based on returned strict expr type

### PR DESCRIPTION
**Pull request by ziegenberg**
This applies the rule **ReturnTypeFromStrictBoolReturnExprRector**. For Details see:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromstrictboolreturnexprrector

### CODE REVIEW

**Comment by ziegenberg** [comment]
Rebased it.

**Comment by ziegenberg** [comment]
Should those PHPDoc `@return` statements also be deleted?

**Comment by JakeQZ** [comment]
> Should those PHPDoc `@return` statements also be deleted?

I think so, if they don't provide anything more than the type hint.

**Review by oliverklee — CHANGES_REQUESTED** [review]
Thanks! Yes, please let's drop those redundant `@return` PHPDoc annotations.

**Comment by ziegenberg** [comment]
Rebased and removed the PHPDoc annotations.

**Review by oliverklee — APPROVED** [review]
LGTM. Thanks! :pray:

**Pull request merged**
