### PR TITLE
[TASK] Remove `Rule::getValues`

### PR DESCRIPTION
**Pull request by ziegenberg**
Removing one function after another.

### CODE REVIEW

**Comment by ziegenberg** [comment]
I fixed the changelog message.

**Comment by ziegenberg** [comment]
Rebased and force-pushed.

**Review by JakeQZ — APPROVED** [review]

**Comment by JakeQZ** [comment]
Sorry, I don't know what's happened here.  I screwed up the merge, so tried to undo it, following [these instructions](https://www.freecodecamp.org/news/git-undo-merge-how-to-revert-the-last-merge-commit-in-git/).  That has resulted in the PR being closed and the changes apparently lost - even though I specifically reset it to the revision before my attempted merge.

**Comment by ziegenberg** [comment]
Just let me fix it.

**Comment by ziegenberg** [comment]
Filed as new PR in #582.

**Comment by JakeQZ** [comment]
It would be useful to know what I did wrong trying to undo the incorrect merge.  I know that `git push` messes up GitHub, so we need `git push -f` - or that's normally the case.  Here's the transcript:

```cmd
D:\git_files\MyIntervals\z\PHP-CSS-Parser>git log
commit 7b18d5a4e3e8430c4b44aca8004b519b5dc5e730 (HEAD -> remove-deprecated-rule-getvalues, origin/remove-deprecated-rule-getvalues)
Merge: c0f577d 8a6c5c7
Author: JakeQZ <jake@qzdesign.co.uk>
Date:   Wed Jun 19 01:09:41 2024 +0100

    Merge branch 'main' into remove-deprecated-rule-getvalues

commit 8a6c5c7ecd3e69fc5942802c31b1b28919a560a1
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 02:01:37 2024 +0200

    [TASK] Remove `Rule::setValues` (#562)

commit e098980a2eb00edecd1683f4877079c3a4674f25
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 01:57:10 2024 +0200

    [TASK] Remove `Document::getAllSelectors` (#561)

commit 0cad1ec2fa2004a49b9846ec10d13dd1f6dac595
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 01:46:58 2024 +0200

    [TASK] Remove `DeclarationBlock::getSelector` (#559)

commit c0f577d2319eeb18c499679fdc288084b8b7183e
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Tue Jun 18 17:13:41 2024 +0200

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git reset --hard 8a6c5c7ecd3e69fc5942802c31b1b28919a560a1
HEAD is now at 8a6c5c7 [TASK] Remove `Rule::setValues` (#562)

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git push -f
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/ziegenberg/PHP-CSS-Parser.git
 + 7b18d5a...8a6c5c7 remove-deprecated-rule-getvalues -> remove-deprecated-rule-getvalues (forced update)

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git log
commit 8a6c5c7ecd3e69fc5942802c31b1b28919a560a1 (HEAD -> remove-deprecated-rule-getvalues, origin/remove-deprecated-rule-getvalues)
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 02:01:37 2024 +0200

    [TASK] Remove `Rule::setValues` (#562)

commit e098980a2eb00edecd1683f4877079c3a4674f25
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 01:57:10 2024 +0200

    [TASK] Remove `Document::getAllSelectors` (#561)

commit 0cad1ec2fa2004a49b9846ec10d13dd1f6dac595
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 01:46:58 2024 +0200

    [TASK] Remove `DeclarationBlock::getSelector` (#559)

commit b979dc8b3cb13cf62d4ad4b7ad6fdfe7bd306677 (origin/main, origin/HEAD, main)
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Tue Jun 18 23:47:58 2024 +0200

    [TASK] Deprecate `DeclarationBlock::expandShorthands` (#558)

    The `expandShorthands`/`createShorthands` functions are deprecated and
    will be removed without substitution in version 10.0.  Expanding and
    creating the shorthand notation is out of the scope of this library.


D:\git_files\MyIntervals\z\PHP-CSS-Parser>git push
Everything up-to-date

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git reset --hard 8a6c5c7ecd3e69fc5942802c31b1b28919a560a1
HEAD is now at 8a6c5c7 [TASK] Remove `Rule::setValues` (#562)

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git push
Everything up-to-date

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git log
commit 8a6c5c7ecd3e69fc5942802c31b1b28919a560a1 (HEAD -> remove-deprecated-rule-getvalues, origin/remove-deprecated-rule-getvalues)
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 02:01:37 2024 +0200

    [TASK] Remove `Rule::setValues` (#562)

commit e098980a2eb00edecd1683f4877079c3a4674f25
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 01:57:10 2024 +0200

    [TASK] Remove `Document::getAllSelectors` (#561)

commit 0cad1ec2fa2004a49b9846ec10d13dd1f6dac595
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Wed Jun 19 01:46:58 2024 +0200

    [TASK] Remove `DeclarationBlock::getSelector` (#559)

commit b979dc8b3cb13cf62d4ad4b7ad6fdfe7bd306677 (origin/main, origin/HEAD, main)
Author: Daniel Ziegenberg <daniel@ziegenberg.at>
Date:   Tue Jun 18 23:47:58 2024 +0200

    [TASK] Deprecate `DeclarationBlock::expandShorthands` (#558)

    The `expandShorthands`/`createShorthands` functions are deprecated and
    will be removed without substitution in version 10.0.  Expanding and
    creating the shorthand notation is out of the scope of this library.


D:\git_files\MyIntervals\z\PHP-CSS-Parser>git push origin
Everything up-to-date

D:\git_files\MyIntervals\z\PHP-CSS-Parser>git pull
From https://github.com/ziegenberg/PHP-CSS-Parser
   b979dc8..8a6c5c7  main       -> origin/main
Already up to date.

D:\git_files\MyIntervals\z\PHP-CSS-Parser>

```

**Pull request closed without merging**
